version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example_password
      POSTGRES_USER: example_user
      POSTGRES_DB: example_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: example_db
      MB_DB_PORT: 5432
      MB_DB_USER: example_user
      MB_DB_PASS: example_password
      MB_DB_HOST: db
    volumes:
      - ./metabase-data:/metabase-data
    ports:
      - "3000:3000"

